export default {
    KR: {
        header: {
            searchPlaceHolder: '검색',
            addVideoPopUp: {
                videoUpload: '동영상 업로드',
                goLive: '실시간 스트리밍 시작',
            },
            appsPopUp: {
                TV: 'YangTube TV',
                music: 'YangTube Music',
                kids: 'YangTube Kids',
                academy: '크리에이터 아카데미',
                artists: 'YangTube for Artists',
            },
            userInfoPopUp: {
                night: {
                    mode: '어두운 테마: ',
                    using: '사용 중',
                    notUsing: '사용 안함',
                    header: '어두운 테마',
                    items: [
                        ['어두운 테마는 페이지의 밝은 표면을 어둡게 해 야간에 적합한 시청 환경을 제공합니다. 어두운 테마를 사용해 보세요.'],
                        ['어두운 테마 설정은 이 브라우저에만 적용 됩니다.'],
                        ['어두운 테마']
                    ]
                },
                language: {
                    mode: '언어: ',
                    KR: '한국어',
                    JP: '日本語',
                    EN: 'English (US)',
                    header: '언어 선택',
                    items: ['한국어', 'English (US)', '日本語'],
                    langCode: ['KR', 'EN', 'JP'],
                },
                location: {
                    mode: '위치: ',
                    KR: '한국',
                    JP: '일본',
                    EN: '미국',
                    header: '위치 선택',
                    items: ['한국', '미국', '일본'],
                    locaCode: ['KR', 'EN', 'JP'],
                },
                config: '설정',
                yourData: 'YangTube의 내 데이터',
                help: '고객센터',
                feedback: '의견 보내기',
            },
        },
        guide: {
            home: '홈',
            trending: '인기',
            subscription: '구독',
            library: '보관함',
            history: '시청 기록',
            best: '인기 YANGTUBE',
            music: '음악',
            sports: '스포츠',
            movies: '영화',
            news: '뉴스',
            live: '실시간',
            learning: '학습',
            video360: '360º 동영상',
            browseCH: '채널 탐색',
            more: 'YANG TAEHWAN 더보기',
            blog: '블로그',
            github: '깃허브',
            settings: '설정',
            report: '신고 기록',
            help: '고객 센터',
            feedback: '의견 보내기',
        },
        video: {},
        title: {},
        desc: {},
        comment: {},
        videoNav: {},
    },
    JP: {},
    EN: {}
};