export default {
    dayMode: {
        header: {
            BG: 'rgba(255, 255, 255, 0.98)',
            searchBoxBG: 'white',
            searchBorder: '#D9D9D9',
            searchBtnBG: '#F0F0F0',
            iconColor: '#5E5E5E',
            plusIconColor: 'white',
            pictogramColor: '#909090',
        },
        guide: {
            BG: 'white',
            footerFont: '#909090',
            pictogramColor: '#909090',
            border: '#E0E0E0',
        },
        main: {
            BG: '#F9F9F9',
            titleInfos: '#909090',
            dislikeRate: '#CCCCCC',
            border: '#E0E0E0',
            subscribedBtnBG: '#ECECEC',
            subscribedBtnFont: 'black',
            commentInputBtn: '#CCCCCC',
            commentInputtingBtn: '#065FD4',
            commentInputBtnTxt: 'white',
            pointerColor: '#065FD4',
        },
        effectBG: 'rgba(0, 0, 0, 0.1)',
        grayFont: '#565656',
        highlightedBG: 'rgba(0, 0, 0, 0.2)',
        normalFont: 'black',
    },
    nightMode: {
        header: {
            BG: 'rgba(32, 32, 32, 0.98)',
            searchBoxBG: '#121212',
            searchBorder: '#313131',
            searchBtnBG: '#313131',
            iconColor: 'white',
            plusIconColor: 'black',
            pictogramColor: '#9A9A9A',
        },
        guide: {
            BG: '#242424',
            footerFont: '#9A9A9A',
            pictogramColor: '#9A9A9A',
            border: '#525252',
        },
        main: {
            BG: '#181818',
            titleInfos: '#909090',
            dislikeRate: '#606060',
            border: '#525252',
            subscribedBtnBG: '#303030',
            subscribedBtnFont: '#9A9A9A',
            commentInputBtn: '#606060',
            commentInputtingBtn: '#3EA6FF',
            commentInputBtnTxt: 'black',
            pointerColor: '#3EA6FF',
        },
        effectBG: 'rgba(255, 255, 255, 0.1)',
        grayFont: '#9A9A9A',
        highlightedBG: 'rgba(255, 255, 255, 0.2)',
        normalFont: 'white',
    }
}